import type { Platform, ProviderMetadata } from '@freellmapi/shared/types.js';

export const PLATFORM_ORDER = [
  'google',
  'groq',
  'cerebras',
  'sambanova',
  'nvidia',
  'mistral',
  'openrouter',
  'github',
  'cohere',
  'cloudflare',
  'zhipu',
  'ollama',
  'kilo',
  'pollinations',
  'llm7',
] as const satisfies readonly Platform[];

export const PROVIDER_METADATA: Record<Platform, ProviderMetadata> = {
  google: {
    platform: 'google',
    displayName: 'Google AI Studio',
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
    keyUrl: 'https://aistudio.google.com/app/apikey',
    consoleUrl: 'https://aistudio.google.com/',
    apiBaseUrl: 'https://generativelanguage.googleapis.com',
    requiresKey: true,
  },
  groq: {
    platform: 'groq',
    displayName: 'Groq',
    docsUrl: 'https://console.groq.com/docs',
    keyUrl: 'https://console.groq.com/keys',
    consoleUrl: 'https://console.groq.com/',
    apiBaseUrl: 'https://api.groq.com/openai/v1',
    requiresKey: true,
  },
  cerebras: {
    platform: 'cerebras',
    displayName: 'Cerebras',
    docsUrl: 'https://inference-docs.cerebras.ai/api-reference/authentication',
    keyUrl: 'https://cloud.cerebras.ai/platform',
    consoleUrl: 'https://cloud.cerebras.ai/platform',
    apiBaseUrl: 'https://api.cerebras.ai/v1',
    requiresKey: true,
  },
  sambanova: {
    platform: 'sambanova',
    displayName: 'SambaNova',
    docsUrl: 'https://docs.sambanova.ai/cloud/docs/get-started/quickstart',
    keyUrl: 'https://cloud.sambanova.ai/',
    consoleUrl: 'https://cloud.sambanova.ai/',
    apiBaseUrl: 'https://api.sambanova.ai/v1',
    requiresKey: true,
  },
  nvidia: {
    platform: 'nvidia',
    displayName: 'NVIDIA NIM',
    docsUrl: 'https://docs.api.nvidia.com/nim/docs/api-quickstart',
    keyUrl: 'https://build.nvidia.com/explore',
    consoleUrl: 'https://build.nvidia.com/',
    apiBaseUrl: 'https://integrate.api.nvidia.com/v1',
    requiresKey: true,
  },
  mistral: {
    platform: 'mistral',
    displayName: 'Mistral',
    docsUrl: 'https://docs.mistral.ai/admin/security-access/api-keys',
    keyUrl: 'https://console.mistral.ai/api-keys',
    consoleUrl: 'https://console.mistral.ai/',
    apiBaseUrl: 'https://api.mistral.ai/v1',
    requiresKey: true,
  },
  openrouter: {
    platform: 'openrouter',
    displayName: 'OpenRouter',
    docsUrl: 'https://openrouter.ai/docs/api/reference/overview',
    keyUrl: 'https://openrouter.ai/settings/keys',
    consoleUrl: 'https://openrouter.ai/',
    apiBaseUrl: 'https://openrouter.ai/api/v1',
    requiresKey: true,
  },
  github: {
    platform: 'github',
    displayName: 'GitHub Models',
    docsUrl: 'https://docs.github.com/en/rest/models/inference?apiVersion=2022-11-28',
    keyUrl: 'https://github.com/settings/personal-access-tokens/new',
    consoleUrl: 'https://github.com/marketplace/models',
    apiBaseUrl: 'https://models.github.ai/inference',
    requiresKey: true,
  },
  cohere: {
    platform: 'cohere',
    displayName: 'Cohere',
    docsUrl: 'https://docs.cohere.com/v2/docs/compatibility-api',
    keyUrl: 'https://dashboard.cohere.com/api-keys',
    consoleUrl: 'https://dashboard.cohere.com/',
    apiBaseUrl: 'https://api.cohere.ai/compatibility/v1',
    requiresKey: true,
  },
  cloudflare: {
    platform: 'cloudflare',
    displayName: 'Cloudflare Workers AI',
    docsUrl: 'https://developers.cloudflare.com/workers-ai/get-started/rest-api/',
    keyUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    consoleUrl: 'https://dash.cloudflare.com/',
    apiBaseUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1',
    requiresKey: true,
  },
  zhipu: {
    platform: 'zhipu',
    displayName: 'Zhipu AI',
    docsUrl: 'https://docs.z.ai/api-reference/',
    keyUrl: 'https://www.bigmodel.cn/usercenter/proj-mgmt/apikeys',
    consoleUrl: 'https://open.bigmodel.cn/',
    apiBaseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    requiresKey: true,
  },
  ollama: {
    platform: 'ollama',
    displayName: 'Ollama Cloud',
    docsUrl: 'https://docs.ollama.com/cloud',
    keyUrl: 'https://ollama.com/settings/keys',
    consoleUrl: 'https://ollama.com/',
    apiBaseUrl: 'https://ollama.com/v1',
    requiresKey: true,
  },
  kilo: {
    platform: 'kilo',
    displayName: 'Kilo Gateway',
    docsUrl: 'https://kilo.ai/docs/gateway',
    keyUrl: 'https://kilo.ai/docs/gateway/authentication',
    consoleUrl: 'https://kilo.ai/',
    apiBaseUrl: 'https://api.kilo.ai/api/gateway/v1',
    requiresKey: false,
  },
  pollinations: {
    platform: 'pollinations',
    displayName: 'Pollinations',
    docsUrl: 'https://github.com/pollinations/pollinations/blob/main/APIDOCS.md',
    keyUrl: 'https://enter.pollinations.ai/',
    consoleUrl: 'https://pollinations.ai/',
    apiBaseUrl: 'https://text.pollinations.ai/openai/v1',
    requiresKey: false,
  },
  llm7: {
    platform: 'llm7',
    displayName: 'LLM7',
    docsUrl: 'https://docs.llm7.io/quickstart',
    keyUrl: 'https://token.llm7.io/',
    consoleUrl: 'https://llm7.io/',
    apiBaseUrl: 'https://api.llm7.io/v1',
    requiresKey: false,
  },
};

export function listProviderMetadata(): ProviderMetadata[] {
  return PLATFORM_ORDER.map(platform => PROVIDER_METADATA[platform]);
}

export function getProviderMetadata(platform: Platform): ProviderMetadata {
  return PROVIDER_METADATA[platform];
}
